language: csharp
sudo: required
dist: trusty

mono: none
dotnet: 2.0.0

solution: ValvePak/ValvePak.sln

notifications:
  email: false

install:
  - dotnet restore ValvePak/ValvePak.sln
script:
  - dotnet build ValvePak/ValvePak.sln --configuration Release
  - dotnet test --configuration Release ValvePak/ValvePak.Test/ValvePak.Test.csproj
