name: CI

permissions:
  actions: write
  contents: write

on: [push, pull_request]

jobs:
  build:
    name: .NET on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build -c Release ValvePak/ValvePak.sln

    - name: Test
      run: dotnet test -c Release ValvePak/ValvePak.Test/ValvePak.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./lcov.info' /p:Include="[ValvePak*]*"

    - name: Create nupkg
      run: dotnet pack --configuration Release ValvePak/ValvePak/ValvePak.csproj

    - name: Upload nupkg
      uses: actions/upload-artifact@v3
      if: matrix.os == 'ubuntu-latest'
      with:
        name: nupkg
        path: 'ValvePak/ValvePak/bin/Release/*.nupkg'

    - name: Upload test coverage
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./ValvePak/ValvePak.Test/lcov.info
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4.1.7
      with:
        path: artifacts

    - name: Display artifacts folder structure
      run: ls -Rl
      working-directory: artifacts

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: artifacts/nupkg/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
