name: .NET Core CI

on: [push, pull_request]

jobs:
  build:
    name: .NET on ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build -c Release ValvePak/ValvePak.sln

    - name: Test
      run: dotnet test -c Release ValvePak/ValvePak.Test/ValvePak.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./lcov.info' /p:Include="[ValvePak*]*"

    - name: Upload test coverage
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./ValvePak/ValvePak.Test/lcov.info
        flag-name: run-${{ matrix.test_number }}
        parallel: true

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
